DUST_REPR := fluid

RES ?= 64
CFL ?= 0.5
POWER ?= -1.0

NVCC += -I $(TST_FLUID_DIR)/verify_common
NVCC += -DVERIFY_RES=$(RES) -DVERIFY_CFL=$(CFL) -DVERIFY_POWER=$(POWER)
NVCC += -DVERIFY_RING -DRADIATION -DDIFFUSION -DCONST_NU -DVERIFY_RING_RADIATION -DVERIFY_RING_DIFFUSION
