RES ?= 64
CFL ?= 0.5
POWER ?= -1.0

NVCC += -I $(ROOT_DIR)/mod/verify_common
NVCC += -DVERIFY_RES=$(RES) -DVERIFY_CFL=$(CFL) -DVERIFY_POWER=$(POWER)
NVCC += -DVERIFY_Z_DIFFUSION -DDIFFUSION -DCONST_NU -DHALFDISK -DVERIFY_UNIFORM_GAS -DVERIFY_CONSTANT_DIFFUSIVITY
