DUST_REPR := swarm
MODEL_PARENT := ../src

GPU_FLAGS += -DTRANSPORT
GPU_FLAGS += -DDIFFUSION
GPU_FLAGS += -DDIFFUSE_CONCENTRATION
GPU_FLAGS += -DCOLLISION
GPU_FLAGS += -DMULTISIZE
GPU_FLAGS += -DSAVE_DENS
