DUST_REPR := fluid

RES ?= 64
CFL ?= 0.5
POWER ?= -1.0
SHIFT ?= 3.25

NVCC += -I $(TST_FLUID_DIR)/verify_common
NVCC += -DVERIFY_RES=$(RES) -DVERIFY_CFL=$(CFL) -DVERIFY_POWER=$(POWER)
NVCC += -DVERIFY_SHIFT=$(SHIFT)
NVCC += -DVERIFY_X_TRANSPORT
